### ISSUE TITLE
sklearn error [fixed], and bace calculation error

### ISSUE THREAD

**Issue by Pixelatory** [jrwnter/mso#7]
I'm trying to use the bace_score_512 and created it as the only scoring function: `ScoringFunction(func=bace_score_512, name="BACE", is_mol_func=False)`

However, I'm receiving this error:

`
Traceback (most recent call last):
  File "test.py", line 33, in <module>
    swarms, EGFR = opt.run(100)
  File "C:\Users\nicka\anaconda3\envs\cddd\lib\site-packages\mso\optimizer.py", line 119, in run
    self.update_fitness(swarm)
  File "C:\Users\nicka\anaconda3\envs\cddd\lib\site-packages\mso\optimizer.py", line 51, in update_fitness
    unscaled_scores, scaled_scores, desirability_scores = scoring_function(swarm.x)
  File "C:\Users\nicka\anaconda3\envs\cddd\lib\site-packages\mso\objectives\scoring.py", line 89, in __call__
    unscaled_scores = self.func(input)
  File "C:\Users\nicka\anaconda3\envs\cddd\lib\site-packages\sklearn\svm\_base.py", line 317, in predict
    return predict(X)
  File "C:\Users\nicka\anaconda3\envs\cddd\lib\site-packages\sklearn\svm\_base.py", line 335, in _dense_predict
    X, self.support_, self.support_vectors_, self._n_support,
AttributeError: 'SVR' object has no attribute '_n_support'
`

What version of scikit-learn was used? I installed cddd first as instructed, downloaded the inference model, then installed mso, and now I'm receiving this error perhaps due to incorrect versioning.

EDIT: Correct version is provided in the comment below.

**Comment by Pixelatory** [comment]
Okay so I actually got it to work with this function using `pip install scikit-learn==0.19.1`, however when using the bace function I'm getting the same results as I did before re-installing. Each iteration of the PSO the max, min, and mean score is always 1.000. In the paper for this project, bace values go much above this.

![image](https://user-images.githubusercontent.com/10425737/153220260-41ad0e36-2e0d-4638-a8c7-e56ab4b13df0.png)

Is there something I'm not doing correctly? The code is able to execute.

**Comment by Pixelatory** [comment]
Sorry never mind. It's because of how scores are scaled that mean was at 1.0, but when I printed out the unscaled scores I can see that individuals do differ in BACE scoring. The main fix to get BACE (and probably EGFR) working is to use `pip install scikit-learn==0.19.1`.
